#!/usr/bin/env python3
"""
HTML to C++ Header Generator
Converts HTML files to C++ string constants for embedded projects
"""

import os
import sys
import re
from pathlib import Path

def minify_html(html_content):
    """
    Minify HTML by removing unnecessary whitespace and comments
    """
    # Remove HTML comments
    html_content = re.sub(r'<!--.*?-->', '', html_content, flags=re.DOTALL)
    
    # Remove extra whitespace between tags
    html_content = re.sub(r'>\s+<', '><', html_content)
    
    # Remove leading/trailing whitespace from lines
    lines = [line.strip() for line in html_content.split('\n')]
    
    # Remove empty lines
    lines = [line for line in lines if line]
    
    # Join lines with minimal spacing
    html_content = ''.join(lines)
    
    return html_content

def escape_string(content):
    """
    Escape string content for C++ string literal
    """
    # Escape backslashes first
    content = content.replace('\\', '\\\\')
    # Escape double quotes
    content = content.replace('"', '\\"')
    # Escape newlines (though we've removed them in minification)
    content = content.replace('\n', '\\n')
    content = content.replace('\r', '\\r')
    
    return content

def html_to_constant_name(filename):
    """
    Convert HTML filename to C++ constant name
    """
    # Remove extension and convert to uppercase
    name = Path(filename).stem.upper()
    # Replace non-alphanumeric characters with underscores
    name = re.sub(r'[^A-Z0-9]', '_', name)
    return f"{name}_HTML"

def generate_header(html_files, output_file):
    """
    Generate C++ header file with HTML constants
    """
    header_content = []
    
    # Header guard
    guard_name = f"_{Path(output_file).stem.upper()}_H_"
    header_content.append(f"#ifndef {guard_name}")
    header_content.append(f"#define {guard_name}")
    header_content.append("")
    header_content.append("// Auto-generated HTML constants")
    header_content.append("// Do not edit this file manually - it will be overwritten")
    header_content.append("")
    
    # Process each HTML file
    for html_file in html_files:
        try:
            with open(html_file, 'r', encoding='utf-8') as f:
                html_content = f.read()
            
            # Minify HTML
            minified = minify_html(html_content)
            
            # Escape for C++ string
            escaped = escape_string(minified)
            
            # Generate constant name
            const_name = html_to_constant_name(html_file)
            
            # Add to header
            header_content.append(f"// Generated from {html_file}")
            header_content.append(f"const char* const {const_name} = \"{escaped}\";")
            header_content.append("")
            
            print(f"Processed: {html_file} -> {const_name}")
            
        except Exception as e:
            print(f"Error processing {html_file}: {e}")
            sys.exit(1)
    
    # Close header guard
    header_content.append(f"#endif // {guard_name}")
    
    # Write header file
    try:
        os.makedirs(os.path.dirname(output_file), exist_ok=True)
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write('\n'.join(header_content))
        print(f"Generated: {output_file}")
    except Exception as e:
        print(f"Error writing {output_file}: {e}")
        sys.exit(1)

def main():
    if len(sys.argv) < 3:
        print("Usage: python html_to_header.py <output_header> <html_file1> [html_file2] ...")
        print("Example: python html_to_header.py src/html_constants.h html/control.html html/configure.html")
        sys.exit(1)
    
    output_file = sys.argv[1]
    html_files = sys.argv[2:]
    
    # Verify all HTML files exist
    for html_file in html_files:
        if not os.path.exists(html_file):
            print(f"Error: HTML file not found: {html_file}")
            sys.exit(1)
    
    print(f"Converting {len(html_files)} HTML file(s) to {output_file}")
    generate_header(html_files, output_file)
    print("Conversion completed successfully!")

if __name__ == "__main__":
    main()